// Brewhouses of the Hanse — simulation dashboard DATA (auto-generated by playtests/dashboard-gen.js).
// Fast sections refresh on each run; SLOW strong-AI sections are static (update after a matchup slate).
window.DASH = {
  "meta": {
    "version": "v1.8 “Quality Pays”",
    "key": "v66",
    "date": "2026-06-20",
    "games": "~3k fast (persona/free-imp) + turn-log feel + 900 strong-AI",
    "note": "Fast sections = persona oracle (committed-lane bots), regenerated by dashboard-gen.js. Strong-AI ladder ran at a throttled bulk budget. Flipped-building feature is bot-untestable."
  },
  "lanes": {
    "fair": {
      "2": 50,
      "3": 33.3,
      "4": 25
    },
    "rows": [
      "prestige",
      "deep",
      "volume",
      "majority",
      "demand"
    ],
    "data": {
      "prestige": {
        "2": 61.7,
        "3": 39.4,
        "4": 27.6
      },
      "deep": {
        "2": 54.2,
        "3": 35.8,
        "4": 27.6
      },
      "volume": {
        "2": 39.8,
        "3": 30.5,
        "4": 20.7
      },
      "majority": {
        "2": 43.1,
        "3": 27.7,
        "4": 27.7
      },
      "demand": {
        "2": 40,
        "3": 31.2,
        "4": 20.6
      }
    },
    "finding": "Prestige (Hall) + Deep dominate heads-up (2p) and converge to fair at 4p. The contested-kontor lanes need a crowd to pay; the Hall is player-count-invariant."
  },
  "scores": {
    "winner": {
      "2": 40,
      "3": 48.1,
      "4": 47.3
    },
    "range": {
      "2": "8–25",
      "3": "9–25",
      "4": "10–25"
    },
    "laneAvg": {
      "prestige": {
        "2": 29.1,
        "3": 39.3,
        "4": 36.9
      },
      "deep": {
        "2": 34.4,
        "3": 40,
        "4": 37
      },
      "volume": {
        "2": 33.3,
        "3": 39.8,
        "4": 35.1
      },
      "majority": {
        "2": 34,
        "3": 38.1,
        "4": 36.5
      },
      "demand": {
        "2": 35,
        "3": 38.5,
        "4": 36
      }
    },
    "finding": "All lanes score within a few points of each other — balance lives in win-rate, not ceiling. Prestige wins more with lower totals (low-variance). Scores peak at 3p."
  },
  "ladder": {
    "rows": [
      {
        "2": 63.3,
        "3": 47.8,
        "4": 30.8,
        "name": "Cellarmaster vs Guildmaster",
        "hi": "CM"
      },
      {
        "2": 70,
        "3": 37,
        "4": 17.5,
        "name": "Cellarmaster vs Trader",
        "hi": "CM"
      },
      {
        "2": 48.3,
        "3": 27.2,
        "4": 14.2,
        "name": "Guildmaster vs Trader",
        "hi": "GM"
      }
    ],
    "finding": "CM > GM at every count. BUT the optimal STRATEGY flips: CM (deep) crushes the Trader 70% at 2p, yet LOSES at 4p — a volume rusher fills the clock before the deep climb matures. (GM throttled here.)"
  },
  "seat": {
    "before": {
      "2": [
        33,
        67
      ],
      "3": [
        22,
        35,
        43
      ],
      "4": [
        15,
        40,
        20,
        25
      ],
      "label": "v63 (with +1G seat comp)"
    },
    "after": {
      "2": [
        50,
        50
      ],
      "label": "v64 (comp removed)"
    },
    "finding": "The +1G/later-seat comp OVER-corrected under strong play (P2 won ~67% at 2p). v1.7 removed it — GMvGM-2p went 33/67 → 50/50."
  },
  "climb": {
    "deliverRate": {
      "q4plus": {
        "2": 6,
        "3": 20,
        "4": 23
      },
      "q5": {
        "2": 15,
        "3": 17,
        "4": 21
      }
    },
    "timeline": [
      {
        "ev": "brew Q2",
        "r": 1
      },
      {
        "ev": "deliver Q2",
        "r": 4
      },
      {
        "ev": "brew Q3",
        "r": 5
      },
      {
        "ev": "full recipes",
        "r": 10
      },
      {
        "ev": "brew Q5",
        "r": 11
      },
      {
        "ev": "deliver Q5",
        "r": 12
      },
      {
        "ev": "game ends",
        "r": 13
      }
    ],
    "finding": "Q5 delivers at median R12 in a ~13-round game — right at the buzzer. Only 15–21% of Trader games ever land a Q5: a committed, high-variance capstone, not a default."
  },
  "improvements": {
    "rows": [
      "hopgarden",
      "granary",
      "cellar",
      "lagering",
      "crane",
      "quay",
      "vessel"
    ],
    "label": {
      "hopgarden": "Hop Garden",
      "granary": "Granary",
      "cellar": "Aging Cellar",
      "lagering": "Lagering",
      "crane": "Harbor Crane",
      "quay": "Private Quay",
      "vessel": "Extra Vessel"
    },
    "data": {
      "hopgarden": {
        "2": 4.8,
        "3": 10.5,
        "4": 7.6
      },
      "granary": {
        "2": 4.8,
        "3": 9.2,
        "4": 9.7
      },
      "cellar": {
        "2": 2.5,
        "3": 1.9,
        "4": 1.3
      },
      "lagering": {
        "2": 2.2,
        "3": -0.8,
        "4": 1.5
      },
      "crane": {
        "2": -4.7,
        "3": -4.2,
        "4": -3.8
      },
      "quay": {
        "2": -1.6,
        "3": -9.6,
        "4": -9.1
      },
      "vessel": {
        "2": -7.9,
        "3": -7.3,
        "4": -7.2
      }
    },
    "finding": "Hop Garden is the clear #1 at every count (the hops-led economy). Throughput perks (Crane/Quay/Vessel) score negative — the greedy bot can't pilot them. Even free, the best is only ~+10% → v1.7 made them cheaper + Cellar-bought."
  },
  "feel": {
    "decisionsPerTurn": 12,
    "roundsAvg": 13.3,
    "skipPct": 1.9,
    "floorToll": {
      "2": {
        "forks": 10.2,
        "toll": 100,
        "floor": 0
      },
      "3": {
        "forks": 22.5,
        "toll": 100,
        "floor": 0
      },
      "4": {
        "forks": 37.9,
        "toll": 100,
        "floor": 0
      }
    },
    "decisionMix": [
      [
        "stops",
        33
      ],
      [
        "cell (Market/Harbor)",
        12
      ],
      [
        "move",
        8
      ],
      [
        "line",
        8
      ],
      [
        "load",
        5
      ],
      [
        "deploy",
        5
      ],
      [
        "brew",
        5
      ],
      [
        "source",
        5
      ],
      [
        "age",
        3
      ],
      [
        "toll",
        2
      ],
      [
        "tap",
        2
      ]
    ],
    "floorSearch": {
      "2": 32,
      "3": 25,
      "4": 26,
      "label": "Guildmaster (search)"
    },
    "finding": "Crisp & efficient: only ~2% of decisions are no-op skips. The Floor (alt-line) is a SUBTLE skill decision — the heuristic Trader pays the 1G toll 100% (never sees it), but the SEARCHING Guildmaster works the Floor 25–32% of the time at the fork. So it's a genuine board-reading choice greedy play (and many humans) under-use, not a dead lane."
  }
};
