// Brewhouses of the Hanse — simulation dashboard DATA (auto-generated by playtests/dashboard-gen.js).
// Fast sections refresh on each run; SLOW strong-AI sections are static (update after a matchup slate).
window.DASH = {
  "meta": {
    "version": "v1.7 “Even Footing”",
    "key": "v64",
    "date": "2026-06-19",
    "games": "~6k fast (persona/free-imp) + turn-log feel + 900 strong-AI",
    "note": "Fast sections = persona oracle (committed-lane bots), regenerated by dashboard-gen.js. Strong-AI ladder ran at a throttled bulk budget. Flipped-building feature is bot-untestable."
  },
  "lanes": {
    "fair": {
      "2": 50,
      "3": 33.3,
      "4": 25
    },
    "rows": [
      "prestige",
      "deep",
      "volume",
      "majority",
      "demand"
    ],
    "data": {
      "prestige": {
        "2": 53.5,
        "3": 40.5,
        "4": 28.1
      },
      "deep": {
        "2": 54.5,
        "3": 36,
        "4": 24.2
      },
      "volume": {
        "2": 40.2,
        "3": 30.8,
        "4": 23.5
      },
      "majority": {
        "2": 44.1,
        "3": 30.9,
        "4": 24.8
      },
      "demand": {
        "2": 44.9,
        "3": 25.5,
        "4": 24.7
      }
    },
    "finding": "Prestige (Hall) + Deep dominate heads-up (2p) and converge to fair at 4p. The contested-kontor lanes need a crowd to pay; the Hall is player-count-invariant."
  },
  "scores": {
    "winner": {
      "2": 39.7,
      "3": 48.7,
      "4": 46.8
    },
    "range": {
      "2": "7–25",
      "3": "9–25",
      "4": "10–25"
    },
    "laneAvg": {
      "prestige": {
        "2": 28,
        "3": 40.5,
        "4": 37.4
      },
      "deep": {
        "2": 34.6,
        "3": 40.4,
        "4": 35.9
      },
      "volume": {
        "2": 33.7,
        "3": 39.1,
        "4": 35.8
      },
      "majority": {
        "2": 34.3,
        "3": 40.3,
        "4": 36
      },
      "demand": {
        "2": 33.8,
        "3": 38.3,
        "4": 35.3
      }
    },
    "finding": "All lanes score within a few points of each other — balance lives in win-rate, not ceiling. Prestige wins more with lower totals (low-variance). Scores peak at 3p."
  },
  "ladder": {
    "rows": [
      {
        "2": 63.3,
        "3": 47.8,
        "4": 30.8,
        "name": "Cellarmaster vs Guildmaster",
        "hi": "CM"
      },
      {
        "2": 70,
        "3": 37,
        "4": 17.5,
        "name": "Cellarmaster vs Trader",
        "hi": "CM"
      },
      {
        "2": 48.3,
        "3": 27.2,
        "4": 14.2,
        "name": "Guildmaster vs Trader",
        "hi": "GM"
      }
    ],
    "finding": "CM > GM at every count. BUT the optimal STRATEGY flips: CM (deep) crushes the Trader 70% at 2p, yet LOSES at 4p — a volume rusher fills the clock before the deep climb matures. (GM throttled here.)"
  },
  "seat": {
    "before": {
      "2": [
        33,
        67
      ],
      "3": [
        22,
        35,
        43
      ],
      "4": [
        15,
        40,
        20,
        25
      ],
      "label": "v63 (with +1G seat comp)"
    },
    "after": {
      "2": [
        50,
        50
      ],
      "label": "v64 (comp removed)"
    },
    "finding": "The +1G/later-seat comp OVER-corrected under strong play (P2 won ~67% at 2p). v1.7 removed it — GMvGM-2p went 33/67 → 50/50."
  },
  "climb": {
    "deliverRate": {
      "q4plus": {
        "2": 6,
        "3": 20,
        "4": 23
      },
      "q5": {
        "2": 15,
        "3": 17,
        "4": 21
      }
    },
    "timeline": [
      {
        "ev": "brew Q2",
        "r": 1
      },
      {
        "ev": "deliver Q2",
        "r": 4
      },
      {
        "ev": "brew Q3",
        "r": 5
      },
      {
        "ev": "full recipes",
        "r": 10
      },
      {
        "ev": "brew Q5",
        "r": 11
      },
      {
        "ev": "deliver Q5",
        "r": 12
      },
      {
        "ev": "game ends",
        "r": 13
      }
    ],
    "finding": "Q5 delivers at median R12 in a ~13-round game — right at the buzzer. Only 15–21% of Trader games ever land a Q5: a committed, high-variance capstone, not a default."
  },
  "improvements": {
    "rows": [
      "hopgarden",
      "granary",
      "cellar",
      "lagering",
      "crane",
      "quay",
      "vessel"
    ],
    "label": {
      "hopgarden": "Hop Garden",
      "granary": "Granary",
      "cellar": "Aging Cellar",
      "lagering": "Lagering",
      "crane": "Harbor Crane",
      "quay": "Private Quay",
      "vessel": "Extra Vessel"
    },
    "data": {
      "hopgarden": {
        "2": 5.9,
        "3": 7.9,
        "4": 7.7
      },
      "granary": {
        "2": 2.6,
        "3": 9.7,
        "4": 6.5
      },
      "cellar": {
        "2": 2.7,
        "3": 2,
        "4": 0.9
      },
      "lagering": {
        "2": -1,
        "3": -0.1,
        "4": -0.4
      },
      "crane": {
        "2": -2.4,
        "3": -5.7,
        "4": -3.9
      },
      "quay": {
        "2": -2.9,
        "3": -4.2,
        "4": -5.5
      },
      "vessel": {
        "2": -5.5,
        "3": -9.9,
        "4": -5.3
      }
    },
    "finding": "Hop Garden is the clear #1 at every count (the hops-led economy). Throughput perks (Crane/Quay/Vessel) score negative — the greedy bot can't pilot them. Even free, the best is only ~+10% → v1.7 made them cheaper + Cellar-bought."
  },
  "feel": {
    "decisionsPerTurn": 12,
    "roundsAvg": 13.1,
    "skipPct": 1.6,
    "floorToll": {
      "2": {
        "forks": 10.1,
        "toll": 100,
        "floor": 0
      },
      "3": {
        "forks": 22.5,
        "toll": 100,
        "floor": 0
      },
      "4": {
        "forks": 37.2,
        "toll": 100,
        "floor": 0
      }
    },
    "decisionMix": [
      [
        "stops",
        33
      ],
      [
        "cell (Market/Harbor)",
        12
      ],
      [
        "move",
        8
      ],
      [
        "line",
        8
      ],
      [
        "load",
        5
      ],
      [
        "deploy",
        5
      ],
      [
        "brew",
        5
      ],
      [
        "source",
        5
      ],
      [
        "age",
        3
      ],
      [
        "toll",
        2
      ],
      [
        "tap",
        2
      ]
    ],
    "finding": "Crisp & efficient: only ~2% of decisions are no-op skips. BUT the Floor (alt-line) is DEAD — the occupied-station fork comes up on up to a third of turns and the AI pays the 1G toll 100% of the time, never working the Floor."
  }
};
